### ISSUE TITLE
Fullstack-project review

### ISSUE THREAD

**Issue by ShootingStar91** [kaifJ/fullstack_open_project#10]
### Fullstack practice project review

This is the review for your fullstack project. It may contain suggestions for improvement, but you do not have to implement those in order to get the credits for your project.

### Feedback on the project (video)

+ The UI seems professional, it has nice distinguishable colours on buttons, and clear positioning
+ Validations on form, good
+ Nice notifications on the upper corner
+ The project seems to fulfill the desired functionality
+ The idea is interesting and the project utilizes an interesting technology
+ Nice filtering functionality

### Feedback on the code

+ Code is generally very readable and well organized
+ Good use of context-api to reduce prop drill
+ Good use of middlewares in the backend as instructed in the fullstackopen-course
+ I would avoid [overusing ternaries](https://github.com/kaifJ/fullstack_open_project/blob/main/frontend/src/components/PropertyList.jsx#L63) - usually a guard clause produces a much more readable component
+ Backend routes could use [express-async-errors](https://fullstackopen.com/en/part4/testing_the_backend#eliminating-the-try-catch)  to reduce try-catch block boilerplate
+ API-tests in backend are a good idea

Altogether, the project looks good and seems easily usable, has a unique idea and implements some interesting technologies. I'm sure it provided some interesting challenge, instead of making just the typical fullstack app! Good work!

**Comment by kaifJ** [comment]
Feedback is much appreciated.
